"""Core env type"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../nbs/005_core.env.ipynb.

# %% auto 0
__all__ = ['BaseEnv']

# %% ../../../nbs/005_core.env.ipynb 4
from abc import ABC
from .llm import BaseChatModel

class BaseEnv(ABC):
    """
    A class to represent the environment iagent.
    """

    def __init__(self):
        self._env = {}

    def register_llm(self, name: str, llm: BaseChatModel):
        self._env[f"llm-{name}"] = llm

    def get_llm(self, name: str) -> BaseChatModel:
        return self._env.get(f"llm-{name}", None)



