"""Some basic core entities like FunctionResult"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../nbs/000_core.function.ipynb.

# %% auto 0
__all__ = ["FunctionResult"]

# %% ../../../nbs/000_core.function.ipynb 4
from typing import Optional, Union

from pydantic import BaseModel, Field

type FunctionInput = Union[str, BaseModel]


class FunctionResult(BaseModel):
    success: bool = Field(..., description="Indicates if the function succeeded")
    output: Union[str, BaseModel] = Field(
        None, description="The output of the function"
    )
    error: Optional[str] = Field(
        None, description="Error message if the function failed"
    )
