"""Some core types in case we want to replace them in future"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../nbs/002_core.llm.ipynb.

# %% auto 0
__all__ = ['BaseChatModel']

# %% ../../../nbs/002_core.llm.ipynb 3
from langchain_core.language_models.chat_models import BaseChatModel as LC_BaseChatLLM

BaseChatModel = LC_BaseChatLLM

