"""Some core types in case we want to replace them in future"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../nbs/001_core.types.ipynb.

# %% auto 0
__all__ = []

# %% ../../../nbs/001_core.types.ipynb 3
import langchain_core.messages as messages

type AIMessage = messages.AIMessage
type AnyMessage = messages.AnyMessage
type BaseMessage = messages.BaseMessage
type ChatMessage = messages.ChatMessage
type FunctionMessage = messages.FunctionMessage
type HumanMessage = messages.HumanMessage
type SystemMessage = messages.SystemMessage
type ToolCall = messages.ToolCall
type ToolMessage = messages.ToolMessage

type AIMessageChunk = messages.AIMessageChunk
type BaseMessageChunk = messages.BaseMessageChunk
type ChatMessageChunk = messages.ChatMessageChunk
type FunctionMessageChunk = messages.FunctionMessageChunk
type HumanMessageChunk = messages.HumanMessageChunk
type SystemMessageChunk = messages.SystemMessageChunk
type ToolCallChunk = messages.ToolCallChunk
type ToolMessageChunk = messages.ToolMessageChunk

