"""Some core types in case we want to replace them in future"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../nbs/001_core.types.ipynb.

# %% auto 0
__all__ = ['AIMessage', 'AnyMessage', 'BaseMessage', 'ChatMessage', 'FunctionMessage', 'HumanMessage', 'SystemMessage',
           'ToolCall', 'ToolMessage', 'AIMessageChunk', 'BaseMessageChunk', 'ChatMessageChunk', 'FunctionMessageChunk',
           'HumanMessageChunk', 'SystemMessageChunk', 'ToolCallChunk', 'ToolMessageChunk']

# %% ../../../nbs/001_core.types.ipynb 3
import langchain_core.messages as messages

AIMessage = messages.AIMessage
AnyMessage = messages.AnyMessage
BaseMessage = messages.BaseMessage
ChatMessage = messages.ChatMessage
FunctionMessage = messages.FunctionMessage
HumanMessage = messages.HumanMessage
SystemMessage = messages.SystemMessage
ToolCall = messages.ToolCall
ToolMessage = messages.ToolMessage

AIMessageChunk = messages.AIMessageChunk
BaseMessageChunk = messages.BaseMessageChunk
ChatMessageChunk = messages.ChatMessageChunk
FunctionMessageChunk = messages.FunctionMessageChunk
HumanMessageChunk = messages.HumanMessageChunk
SystemMessageChunk = messages.SystemMessageChunk
ToolCallChunk = messages.ToolCallChunk
ToolMessageChunk = messages.ToolMessageChunk

