# Autogenerated by nbdev

d = {
    "settings": {
        "branch": "main",
        "doc_baseurl": "/iagent/",
        "doc_host": "https://blackcherry88.github.io",
        "git_url": "https://github.com/blackcherry88/iagent/",
        "lib_path": "src/iagent",
    },
    "syms": {
        "iagent.ai.messages": {
            "iagent.ai.messages.Annotation": (
                "ai.types.html#annotation",
                "iagent/ai/messages.py",
            ),
            "iagent.ai.messages.AnnotationURLCitation": (
                "ai.types.html#annotationurlcitation",
                "iagent/ai/messages.py",
            ),
            "iagent.ai.messages.AssistantAudio": (
                "ai.types.html#assistantaudio",
                "iagent/ai/messages.py",
            ),
            "iagent.ai.messages.AssistantMessage": (
                "ai.types.html#assistantmessage",
                "iagent/ai/messages.py",
            ),
            "iagent.ai.messages.ChatCompletionMessage": (
                "ai.types.html#chatcompletionmessage",
                "iagent/ai/messages.py",
            ),
            "iagent.ai.messages.Choice": (
                "ai.types.html#choice",
                "iagent/ai/messages.py",
            ),
            "iagent.ai.messages.CompletionUsage": (
                "ai.types.html#completionusage",
                "iagent/ai/messages.py",
            ),
            "iagent.ai.messages.Function": (
                "ai.types.html#function",
                "iagent/ai/messages.py",
            ),
            "iagent.ai.messages.ImageURL": (
                "ai.types.html#imageurl",
                "iagent/ai/messages.py",
            ),
            "iagent.ai.messages.InputAudio": (
                "ai.types.html#inputaudio",
                "iagent/ai/messages.py",
            ),
            "iagent.ai.messages.PartImage": (
                "ai.types.html#partimage",
                "iagent/ai/messages.py",
            ),
            "iagent.ai.messages.PartInputAudio": (
                "ai.types.html#partinputaudio",
                "iagent/ai/messages.py",
            ),
            "iagent.ai.messages.PartText": (
                "ai.types.html#parttext",
                "iagent/ai/messages.py",
            ),
            "iagent.ai.messages.ToolCallMessage": (
                "ai.types.html#toolcallmessage",
                "iagent/ai/messages.py",
            ),
            "iagent.ai.messages.UserMessage": (
                "ai.types.html#usermessage",
                "iagent/ai/messages.py",
            ),
            "iagent.ai.messages.UserMessage.addPart": (
                "ai.types.html#usermessage.addpart",
                "iagent/ai/messages.py",
            ),
        },
        "iagent.ai.service": {},
        "iagent.core.env": {
            "iagent.core.env.BaseEnv": ("core.env.html#baseenv", "iagent/core/env.py"),
            "iagent.core.env.BaseEnv.__init__": (
                "core.env.html#baseenv.__init__",
                "iagent/core/env.py",
            ),
            "iagent.core.env.BaseEnv.get_llm": (
                "core.env.html#baseenv.get_llm",
                "iagent/core/env.py",
            ),
            "iagent.core.env.BaseEnv.register_llm": (
                "core.env.html#baseenv.register_llm",
                "iagent/core/env.py",
            ),
        },
        "iagent.core.funtion": {
            "iagent.core.funtion.FunctionResult": (
                "core.function.html#functionresult",
                "iagent/core/funtion.py",
            )
        },
        "iagent.mcp": {},
        "iagent.task": {
            "iagent.task.Task": ("task.html#task", "iagent/task.py"),
            "iagent.task.Task._notify": ("task.html#task._notify", "iagent/task.py"),
            "iagent.task.Task.add_listener": (
                "task.html#task.add_listener",
                "iagent/task.py",
            ),
            "iagent.task.Task.add_sub_task": (
                "task.html#task.add_sub_task",
                "iagent/task.py",
            ),
            "iagent.task.Task.complete": ("task.html#task.complete", "iagent/task.py"),
            "iagent.task.Task.fail": ("task.html#task.fail", "iagent/task.py"),
            "iagent.task.Task.from_instruction": (
                "task.html#task.from_instruction",
                "iagent/task.py",
            ),
            "iagent.task.Task.remove_listener": (
                "task.html#task.remove_listener",
                "iagent/task.py",
            ),
            "iagent.task.Task.remove_sub_task": (
                "task.html#task.remove_sub_task",
                "iagent/task.py",
            ),
            "iagent.task.Task.run": ("task.html#task.run", "iagent/task.py"),
            "iagent.task.Task.start": ("task.html#task.start", "iagent/task.py"),
            "iagent.task.TaskEvent": ("task.html#taskevent", "iagent/task.py"),
            "iagent.task.TaskListener": ("task.html#tasklistener", "iagent/task.py"),
            "iagent.task.TaskListener.on_event": (
                "task.html#tasklistener.on_event",
                "iagent/task.py",
            ),
            "iagent.task.TaskStatus": ("task.html#taskstatus", "iagent/task.py"),
        },
    },
}
