# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/iagent/',
                'doc_host': 'https://blackcherry88.github.io',
                'git_url': 'https://github.com/blackcherry88/iagent/',
                'lib_path': 'src/iagent'},
  'syms': { 'iagent.core': {'iagent.core.foo': ('core.html#foo', 'iagent/core.py')},
            'iagent.task': {'iagent.task.Task': ('task.html#task', 'iagent/task.py')},
            'iagent.tool.tool_spec': {},
            'iagent.tool2': {}}}
