# Autogenerated by nbdev

d = {
    "settings": {
        "branch": "main",
        "doc_baseurl": "/iagent/",
        "doc_host": "https://blackcherry88.github.io",
        "git_url": "https://github.com/blackcherry88/iagent/",
        "lib_path": "src/iagent",
    },
    "syms": {
        "iagent.ai.imp.openai": {
            "iagent.ai.imp.openai.OpenAI": (
                "ai.imp.openai.html#openai",
                "iagent/ai/imp/openai.py",
            ),
            "iagent.ai.imp.openai.OpenAI.__init__": (
                "ai.imp.openai.html#openai.__init__",
                "iagent/ai/imp/openai.py",
            ),
            "iagent.ai.imp.openai.OpenAI.chat": (
                "ai.imp.openai.html#openai.chat",
                "iagent/ai/imp/openai.py",
            ),
        },
        "iagent.ai.messages": {
            "iagent.ai.messages.Annotation": (
                "ai.messages.html#annotation",
                "iagent/ai/messages.py",
            ),
            "iagent.ai.messages.AnnotationURLCitation": (
                "ai.messages.html#annotationurlcitation",
                "iagent/ai/messages.py",
            ),
            "iagent.ai.messages.AssistantAudio": (
                "ai.messages.html#assistantaudio",
                "iagent/ai/messages.py",
            ),
            "iagent.ai.messages.AssistantMessage": (
                "ai.messages.html#assistantmessage",
                "iagent/ai/messages.py",
            ),
            "iagent.ai.messages.Function": (
                "ai.messages.html#function",
                "iagent/ai/messages.py",
            ),
            "iagent.ai.messages.HistoryMessage": (
                "ai.messages.html#historymessage",
                "iagent/ai/messages.py",
            ),
            "iagent.ai.messages.HistoryMessage.__init__": (
                "ai.messages.html#historymessage.__init__",
                "iagent/ai/messages.py",
            ),
            "iagent.ai.messages.HistoryMessage.addMessage": (
                "ai.messages.html#historymessage.addmessage",
                "iagent/ai/messages.py",
            ),
            "iagent.ai.messages.HistoryMessage.from_json": (
                "ai.messages.html#historymessage.from_json",
                "iagent/ai/messages.py",
            ),
            "iagent.ai.messages.HistoryMessage.to_dict": (
                "ai.messages.html#historymessage.to_dict",
                "iagent/ai/messages.py",
            ),
            "iagent.ai.messages.HistoryMessage.to_json": (
                "ai.messages.html#historymessage.to_json",
                "iagent/ai/messages.py",
            ),
            "iagent.ai.messages.ImageURL": (
                "ai.messages.html#imageurl",
                "iagent/ai/messages.py",
            ),
            "iagent.ai.messages.InputAudio": (
                "ai.messages.html#inputaudio",
                "iagent/ai/messages.py",
            ),
            "iagent.ai.messages.PartImage": (
                "ai.messages.html#partimage",
                "iagent/ai/messages.py",
            ),
            "iagent.ai.messages.PartInputAudio": (
                "ai.messages.html#partinputaudio",
                "iagent/ai/messages.py",
            ),
            "iagent.ai.messages.PartText": (
                "ai.messages.html#parttext",
                "iagent/ai/messages.py",
            ),
            "iagent.ai.messages.ToolCall": (
                "ai.messages.html#toolcall",
                "iagent/ai/messages.py",
            ),
            "iagent.ai.messages.ToolResponseMessage": (
                "ai.messages.html#toolresponsemessage",
                "iagent/ai/messages.py",
            ),
            "iagent.ai.messages.UserMessage": (
                "ai.messages.html#usermessage",
                "iagent/ai/messages.py",
            ),
            "iagent.ai.messages.UserMessage.addPart": (
                "ai.messages.html#usermessage.addpart",
                "iagent/ai/messages.py",
            ),
        },
        "iagent.ai.responses": {
            "iagent.ai.responses.ChatCompletionResponse": (
                "ai.responses.html#chatcompletionresponse",
                "iagent/ai/responses.py",
            ),
            "iagent.ai.responses.Choice": (
                "ai.responses.html#choice",
                "iagent/ai/responses.py",
            ),
            "iagent.ai.responses.CompletionUsage": (
                "ai.responses.html#completionusage",
                "iagent/ai/responses.py",
            ),
        },
        "iagent.ai.service": {
            "iagent.ai.service.ChatClientBase": (
                "ai.service.html#chatclientbase",
                "iagent/ai/service.py",
            ),
            "iagent.ai.service.ChatClientBase.__init__": (
                "ai.service.html#chatclientbase.__init__",
                "iagent/ai/service.py",
            ),
            "iagent.ai.service.ChatClientBase.chat": (
                "ai.service.html#chatclientbase.chat",
                "iagent/ai/service.py",
            ),
            "iagent.ai.service.ChatSettings": (
                "ai.service.html#chatsettings",
                "iagent/ai/service.py",
            ),
        },
        "iagent.core.funtion": {
            "iagent.core.funtion.FunctionResult": (
                "core.function.html#functionresult",
                "iagent/core/funtion.py",
            )
        },
        "iagent.mcp": {},
        "iagent.task": {
            "iagent.task.Task": ("task.html#task", "iagent/task.py"),
            "iagent.task.Task._notify": ("task.html#task._notify", "iagent/task.py"),
            "iagent.task.Task.add_listener": (
                "task.html#task.add_listener",
                "iagent/task.py",
            ),
            "iagent.task.Task.add_sub_task": (
                "task.html#task.add_sub_task",
                "iagent/task.py",
            ),
            "iagent.task.Task.complete": ("task.html#task.complete", "iagent/task.py"),
            "iagent.task.Task.fail": ("task.html#task.fail", "iagent/task.py"),
            "iagent.task.Task.from_instruction": (
                "task.html#task.from_instruction",
                "iagent/task.py",
            ),
            "iagent.task.Task.remove_listener": (
                "task.html#task.remove_listener",
                "iagent/task.py",
            ),
            "iagent.task.Task.remove_sub_task": (
                "task.html#task.remove_sub_task",
                "iagent/task.py",
            ),
            "iagent.task.Task.run": ("task.html#task.run", "iagent/task.py"),
            "iagent.task.Task.start": ("task.html#task.start", "iagent/task.py"),
            "iagent.task.TaskEvent": ("task.html#taskevent", "iagent/task.py"),
            "iagent.task.TaskListener": ("task.html#tasklistener", "iagent/task.py"),
            "iagent.task.TaskListener.on_event": (
                "task.html#tasklistener.on_event",
                "iagent/task.py",
            ),
            "iagent.task.TaskStatus": ("task.html#taskstatus", "iagent/task.py"),
        },
    },
}
