"""Some basic core entities like FunctionInput and FunctionOutput"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/000_core.ipynb.

# %% auto 0
__all__ = ['FunctionInput', 'FunctionResult']

# %% ../../nbs/000_core.ipynb 3
from typing import Union, Optional
from pydantic import BaseModel, Field

FunctionInput = Union[str, BaseModel]

class FunctionResult(BaseModel):
    success: bool = Field(..., description="Indicates if the function succeeded")
    output: Union[str, BaseModel] = Field(None, description="The output of the function")
    error: Optional[str] = Field(None, description="Error message if the function failed")


