"""Basic function for MCP Tool"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/010_mcp.ipynb.

# %% auto 0
__all__ = ['load_mcp_tools']

# %% ../../nbs/010_mcp.ipynb 4
from langchain_mcp_adapters.tools import (
    load_mcp_tools as lc_load_mcp_tools,
)

load_mcp_tools = lc_load_mcp_tools
