"""Fill in a module description here"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/000_task.ipynb.

# %% auto 0
__all__ = ['Task']

# %% ../../nbs/000_task.ipynb 3
class Task:
    """
    Represents a task to be performed within a session, potentially with subtasks.
    """
    pass
