"""Define message types"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../nbs/000_ai.messages.ipynb.

# %% auto 0
__all__ = [
    "ContentPart",
    "AnyMessage",
    "InputAudio",
    "PartInputAudio",
    "ImageURL",
    "PartImage",
    "PartText",
    "UserMessage",
    "ToolResponseMessage",
    "AnnotationURLCitation",
    "Annotation",
    "AssistantAudio",
    "Function",
    "ToolCall",
    "AssistantMessage",
    "HistoryMessage",
]

import json
# %% ../../../nbs/000_ai.messages.ipynb 3
from dataclasses import dataclass
from typing import List, Optional, Union

from pydantic import BaseModel
from typing_extensions import Literal, TypeAlias

#
# The type definitions are adapted by reference on OPENAI specifications.
# but decide to go with dataclass instead of TypedDict
#


@dataclass
class InputAudio:
    data: str
    """Base64 encoded audio data."""

    format: Literal["wav", "mp3"]
    """The format of the encoded audio data."""


@dataclass
class PartInputAudio:
    input_audio: InputAudio

    type: Optional[Literal["input_audio"]] = "input_audio"
    """The type of the content part. Always `input_audio`."""


@dataclass
class ImageURL:
    url: str
    """Either a URL of the image or the base64 encoded image data."""

    detail: Optional[Literal["auto", "low", "high"]] = None
    """Specifies the detail level of the image."""


@dataclass
class PartImage:
    image_url: ImageURL

    type: Optional[Literal["image_url"]] = "image_url"
    """The type of the content part."""


@dataclass
class PartText:
    text: str
    """The text content."""

    type: Optional[Literal["text"]] = "text"
    """The type of the content part."""


ContentPart: TypeAlias = Union[
    PartText,
    PartImage,
    PartInputAudio,
]


class UserMessage(BaseModel):
    content: Union[str, List[ContentPart]]
    """The contents of the user message."""

    role: Literal["user"] = "user"
    """The role of the messages author, in this case `user`."""

    def addPart(self, part: ContentPart):
        """
        Add a ContentPart to the message content. If content is a string, it will be converted to a list.
        """
        if isinstance(self.content, str):
            self.content = [PartText(text=self.content)]
        if not isinstance(self.content, list):
            self.content = []
        self.content.append(part)


class ToolResponseMessage(BaseModel):
    content: Union[str, List[PartText]]
    """The contents of the tool message."""

    role: Literal["tool"] = "tool"
    """The role of the messages author, in this case `tool`."""

    tool_call_id: Optional[str] = None
    """Tool call that this message is responding to."""


class AnnotationURLCitation(BaseModel):
    end_index: int
    """The index of the last character of the URL citation in the message."""

    start_index: int
    """The index of the first character of the URL citation in the message."""

    title: str
    """The title of the web resource."""

    url: str
    """The URL of the web resource."""


class Annotation(BaseModel):
    type: Literal["url_citation"]
    """The type of the URL citation. Always `url_citation`."""

    url_citation: AnnotationURLCitation
    """A URL citation when using web search."""


class AssistantAudio(BaseModel):
    id: str
    """Unique identifier for this audio response."""

    data: str
    """
    Base64 encoded audio bytes generated by the model, in the format specified in
    the request.
    """

    expires_at: int
    """
    The Unix timestamp (in seconds) for when this audio response will no longer be
    accessible on the server for use in multi-turn conversations.
    """

    transcript: str
    """Transcript of the audio generated by the model."""


class Function(BaseModel):
    arguments: str
    """
    The arguments to call the function with, as generated by the model in JSON
    format. Note that the model does not always generate valid JSON, and may
    hallucinate parameters not defined by your function schema. Validate the
    arguments in your code before calling your function.
    """

    name: str
    """The name of the function to call."""


class ToolCall(BaseModel):
    id: str
    """The ID of the tool call."""

    function: Function
    """The function that the model called."""

    type: Literal["function"]
    """The type of the tool. Currently, only `function` is supported."""


class AssistantMessage(BaseModel):
    content: Optional[str] = None
    """The contents of the message."""

    refusal: Optional[str] = None
    """The refusal message generated by the model."""

    role: Literal["assistant"] = "assistant"
    """The role of the author of this message."""

    annotations: Optional[List[Annotation]] = None
    """
    Annotations for the message, when applicable, as when using the
    """

    audio: Optional[AssistantAudio] = None
    """
    If the audio output modality is requested, this object contains data about the
    audio response from the model.
    """

    tool_calls: Optional[List[ToolCall]] = None
    """The tool calls generated by the model, such as function calls."""

    model_config = {"extra": "allow"}


AnyMessage: TypeAlias = Union[
    UserMessage,
    AssistantMessage,
    ToolResponseMessage,
]


class HistoryMessage:
    """
    A message in the conversation history. This class is used to store messages
    in the conversation history, regardless of their type.
    """

    messages: List[AnyMessage]
    """The list of messages in the conversation history."""

    def __init__(self, messages: List[AnyMessage] = None):
        """
        Initialize the conversation history with an empty list of messages.
        """
        if messages is None:
            messages = []
        self.messages = messages

    def addMessage(self, message: AnyMessage):
        """
        Add a message to the conversation history.
        """
        self.messages.append(message)

    def to_json(self):
        """
        Convert the conversation history to JSON format.
        """
        return [message.model_dump_json() for message in self.messages]

    def to_dict(self):
        """
        Convert the conversation history to JSON format.
        """
        return [message.model_dump() for message in self.messages]

    def from_json(self, json_data: List[str]):
        """
        Load the conversation history from JSON format.
        """
        self.messages = []
        for message_json in json_data:
            # Parse the JSON string to get a dictionary
            message_dict = json.loads(message_json)

            # Determine the message type based on the role
            role = message_dict.get("role")
            if role == "user":
                message = UserMessage.model_validate_json(message_json)
            elif role == "assistant":
                message = AssistantMessage.model_validate_json(message_json)
            elif role == "tool":
                message = ToolResponseMessage.model_validate_json(message_json)
            else:
                raise ValueError(f"Unknown message role: {role}")

            self.messages.append(message)
