"""Define basic ai service"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../nbs/002_ai.service.ipynb.

# %% auto 0
__all__ = ["ChatSettings", "ChatClientBase"]

# %% ../../../nbs/002_ai.service.ipynb 4
from abc import ABC
from dataclasses import dataclass
from typing import List, Optional

from .messages import AnyMessage
from .responses import ChatCompletionResponse


@dataclass
class ChatSettings:
    temperature: Optional[float] = None
    top_k: Optional[int] = None
    top_p: Optional[float] = None
    max_tokens: Optional[int] = None
    max_new_tokens: Optional[int] = None
    frequency_penalty: Optional[float] = None
    presence_penalty: Optional[float] = None


class ChatClientBase(ABC):
    def __init__(self, settings: ChatSettings = None):
        self.settings = settings

    def chat(
        self, model_id: str, messages: List[AnyMessage], setting: ChatSettings = None
    ) -> ChatCompletionResponse:
        raise NotImplementedError
