"""Some core types in case we want to replace them in future"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../nbs/002_ai.service.ipynb.

# %% auto 0
__all__ = ["BaseChatModel"]

# %% ../../../nbs/002_ai.service.ipynb 3
import langchain_core.language_models.chat_models as models

BaseChatModel = models.BaseChatModel
